apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlzbu3145-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlzbu3145-tenant-component
    app.kubernetes.io/part-of: loadlzbu3145-tenant-app
  name: loadlzbu3145-tenant-component
  namespace: loadlzbu3145-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadlzbu3145-tenant-component
    weight: null
status: {}
